# Generated by Django 4.1.5 on 2023-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
                ('slug', models.SlugField(null=True, verbose_name='Slug Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fotograf')),
                ('tetx', models.TextField(max_length=1000, verbose_name='Resim Hakkında')),
                ('image', models.ImageField(upload_to='photo', verbose_name='Resim')),
            ],
        ),
    ]
