# Generated by Django 4.1.5 on 2023-03-14 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(verbose_name='Doğum Yılı')),
                ('age', models.IntegerField(verbose_name='Yaş')),
                ('website', models.URLField(verbose_name='Website')),
                ('degree', models.CharField(max_length=50, verbose_name='Tahsil')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('city', models.CharField(max_length=50, verbose_name='Yaşadığınız Yer')),
                ('job', models.CharField(max_length=50, verbose_name='İş')),
                ('text', models.TextField(max_length=1000, verbose_name='Hakkımda')),
                ('image', models.ImageField(default='img7.jfif', upload_to='', verbose_name='Profil Resmi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
