# Generated by Django 4.1.5 on 2023-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Doğum Yılı'),
        ),
    ]
