# Generated by Django 4.1.5 on 2023-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_alter_profil_age_alter_profil_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Yaş'),
        ),
    ]
